### ISSUE TITLE
Bug: remove 0 character length from the slider

### ISSUE THREAD

**Issue by Nafsuki** [Murci2022/Password-generator#11]
- As you pointed out, currently slider includes 0 character which doesn't make sense and breaks the design. 
Please remove 0 character length option, so user can choose between `1 - 12` character letters.

<img width="443" alt="Screenshot 2023-07-29 at 14 04 59" src="https://github.com/Murci2022/Password-generator/assets/48878455/d5ada4a4-ce10-4229-adcb-6c5dd4d174fb">

**Comment by Murci2022** [comment]
Fixed with PR #13
